import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { AppContextProvider } from "@/store";
import { Layout } from "@/layout";

const nunito = Nunito({
  subsets: ["latin", "latin-ext"],
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <AppContextProvider>
          <Layout>{children}</Layout>
        </AppContextProvider>
      </body>
    </html>
  );
}
