import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import { AppContextProvider } from "@/store";
import { Layout } from "@/layout";

import "./globals.css";

const inter = Inter({
  subsets: ["latin", "latin-ext"],
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  subsets: ["latin", "latin-ext"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfair.variable} light h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <AppContextProvider>
          <Layout>{children}</Layout>
        </AppContextProvider>
      </body>
    </html>
  );
}
